name = "Convert Hex Color to Tailwind Preset"
description = "Command to convert hex color to Tailwind preset"
endpointURL = "https://tailwind-color-finder.vercel.app/api/slapdash/hex-to-tailwind-command"
sourceCodeURL = "https://github.com/TedisAgolli/tailwind-color-finder/blob/master/pages/api/slapdash/hex-to-tailwind-command.js"

language = "javascript"
categories = ["Developer Tools", "Utilities"]

author.name = "Tedis Agolli"
author.profileURL = "https://twitter.com/TedisAgolli"

readme = """
Pass a valid hex color, e.g. #fff and the command will return the closest
Tailwind preset; in this case true-gray-50

Below the color you will see the Delta-E, which is the difference between the two colors.
There will also a plain language explanation of the Delta-E, such as "Perceptible through close observation".
Here is a source explaining [Delta-E](http://zschuessler.github.io/DeltaE/learn/)
"""
